language: node_js
sudo: false
node_js:
  - "6.0"
install:
  - npm install
script:
  - npm test
env:
  - FACEBOOK_APP_ID=dummy
  - FACEBOOK_APP_SECRET=dummy
  - GOOGLE_APP_ID=dummy
  - GOOGLE_APP_SECRET=dummy
